### ISSUE TITLE
Addon sign-on credentials wont authenticate within Kodi 17.6 for Android TV.

### ISSUE THREAD

**Issue by ssmith1936** [bbsan2k/repository.f1tv#1]
Installed this app on 2 devices:  a.) RBPi3B and b.) Nvidia Shield with latest Android TV.   Works great on my Raspberi Pi 3B on KODI 17.6 w/ Libreelec.     I loaded your release 5 zip file from github via a usb drive.   It did take several clicks to get the race video links to start playing video. I got the 'item failed to play' message 1-2 times before it would play.  But it did play and played, FF, RW etc. well....works fine on the RBPi3B.

I then loaded the same F1TV release 5 zip onto my Nvidia Shield with Android TV running a KODI 17.6.  The app loaded after a couple of attempts.  I then entered my login info and started the addon.  I got to the menu within the addon , and I browsed to and selected a race to play, but got an error message that indicated that my logon was not authenticated and I needed to go to settings to check/reenter my credentials. This started a loop where I was forced to either reenter my logon Id and password or hit ok and  get the same 'logon credentials not authenticated' error.  Hitting escape would kick me out of the addon within kodi.  I could not play a video on the Android TV device.

Hope this helps in your troubleshooting.  I like using it on my RBPi so far.

**Comment by bbsan2k** [comment]
Issue is related to Plugin, not repository.

Still:
Try to clear your device list in F1TV websites settings.
